version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    build: .
    restart: always
    depends_on:
      - postgres
    tty: true
    environment:
      - POSTGRES_HOST=postgres
    env_file:
      - .env

volumes:
  postgres_db:
    driver: local
