version: "3.9"

services:
  db:
    hostname: db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    build: .
    restart: on-failure
    depends_on:
      - db
    tty: true
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    links:
      - db:db

volumes:
  postgres_db:
    driver: local

networks:
  default:
    driver: bridge
